/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Temp title
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ArticleEntity,
  ArticlesResponseDto,
  AuthEntity,
  CommentEntity,
  CreateArticleDto,
  CreateCommentDto,
  CreateUserDto,
  GetAllArticlesParams,
  LoginDto,
  UpdateArticleDto,
  UpdateUserDto,
  UserEntity
} from './model';

import { customInstance } from './custom-instance';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getAllUsersResponse200 = {
  data: UserEntity[]
  status: 200
}

export type getAllUsersResponseSuccess = (getAllUsersResponse200) & {
  headers: Headers;
};
;

export type getAllUsersResponse = (getAllUsersResponseSuccess)

export const getGetAllUsersUrl = () => {


  

  return `/api/users`
}

export const getAllUsers = async ( options?: RequestInit): Promise<getAllUsersResponse> => {
  
  return customInstance<getAllUsersResponse>(getGetAllUsersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetAllUsersQueryKey = () => {
    return [
    `/api/users`
    ] as const;
    }

    
export const getGetAllUsersQueryOptions = <TData = Awaited<ReturnType<typeof getAllUsers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllUsersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllUsers>>> = ({ signal }) => getAllUsers({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   error: 'AxiosError<ErrorResponseDto>',  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getAllUsers>>>
export type GetAllUsersQueryError = unknown


export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllUsers>>,
          TError,
          Awaited<ReturnType<typeof getAllUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllUsers>>,
          TError,
          Awaited<ReturnType<typeof getAllUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type getMeResponse200 = {
  data: UserEntity
  status: 200
}

export type getMeResponseSuccess = (getMeResponse200) & {
  headers: Headers;
};
;

export type getMeResponse = (getMeResponseSuccess)

export const getGetMeUrl = () => {


  

  return `/api/users/me`
}

export const getMe = async ( options?: RequestInit): Promise<getMeResponse> => {
  
  return customInstance<getMeResponse>(getGetMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetMeQueryKey = () => {
    return [
    `/api/users/me`
    ] as const;
    }

    
export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   error: 'AxiosError<ErrorResponseDto>',  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = unknown


export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type updateMeResponse200 = {
  data: UserEntity
  status: 200
}

export type updateMeResponseSuccess = (updateMeResponse200) & {
  headers: Headers;
};
;

export type updateMeResponse = (updateMeResponseSuccess)

export const getUpdateMeUrl = () => {


  

  return `/api/users/me`
}

export const updateMe = async (updateUserDto: UpdateUserDto, options?: RequestInit): Promise<updateMeResponse> => {
  
  return customInstance<updateMeResponse>(getUpdateMeUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUserDto,)
  }
);}
  



export const getUpdateMeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMe>>, TError,{data: UpdateUserDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMe>>, TError,{data: UpdateUserDto}, TContext> => {

const mutationKey = ['updateMe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMe>>, {data: UpdateUserDto}> = (props) => {
          const {data} = props ?? {};

          return  updateMe(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMeMutationResult = NonNullable<Awaited<ReturnType<typeof updateMe>>>
    export type UpdateMeMutationBody = UpdateUserDto
    export type UpdateMeMutationError = unknown

    export const useUpdateMe = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMe>>, TError,{data: UpdateUserDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMe>>,
        TError,
        {data: UpdateUserDto},
        TContext
      > => {
      return useMutation(getUpdateMeMutationOptions(options), queryClient);
    }
    
export type loginResponse200 = {
  data: AuthEntity
  status: 200
}

export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
;

export type loginResponse = (loginResponseSuccess)

export const getLoginUrl = () => {


  

  return `/api/auth/login`
}

export const login = async (loginDto: LoginDto, options?: RequestInit): Promise<loginResponse> => {
  
  return customInstance<loginResponse>(getLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginDto,)
  }
);}
  



export const getLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginDto}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: LoginDto}> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = LoginDto
    export type LoginMutationError = unknown

    export const useLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: LoginDto},
        TContext
      > => {
      return useMutation(getLoginMutationOptions(options), queryClient);
    }
    
export type registerResponse200 = {
  data: AuthEntity
  status: 200
}

export type registerResponseSuccess = (registerResponse200) & {
  headers: Headers;
};
;

export type registerResponse = (registerResponseSuccess)

export const getRegisterUrl = () => {


  

  return `/api/auth/register`
}

export const register = async (createUserDto: CreateUserDto, options?: RequestInit): Promise<registerResponse> => {
  
  return customInstance<registerResponse>(getRegisterUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createUserDto,)
  }
);}
  



export const getRegisterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: CreateUserDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: CreateUserDto}, TContext> => {

const mutationKey = ['register'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, {data: CreateUserDto}> = (props) => {
          const {data} = props ?? {};

          return  register(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
    export type RegisterMutationBody = CreateUserDto
    export type RegisterMutationError = unknown

    export const useRegister = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: CreateUserDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof register>>,
        TError,
        {data: CreateUserDto},
        TContext
      > => {
      return useMutation(getRegisterMutationOptions(options), queryClient);
    }
    
export type createArticleResponse201 = {
  data: ArticleEntity
  status: 201
}

export type createArticleResponseSuccess = (createArticleResponse201) & {
  headers: Headers;
};
;

export type createArticleResponse = (createArticleResponseSuccess)

export const getCreateArticleUrl = () => {


  

  return `/api/articles`
}

export const createArticle = async (createArticleDto: CreateArticleDto, options?: RequestInit): Promise<createArticleResponse> => {
  
  return customInstance<createArticleResponse>(getCreateArticleUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createArticleDto,)
  }
);}
  



export const getCreateArticleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createArticle>>, TError,{data: CreateArticleDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createArticle>>, TError,{data: CreateArticleDto}, TContext> => {

const mutationKey = ['createArticle'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createArticle>>, {data: CreateArticleDto}> = (props) => {
          const {data} = props ?? {};

          return  createArticle(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateArticleMutationResult = NonNullable<Awaited<ReturnType<typeof createArticle>>>
    export type CreateArticleMutationBody = CreateArticleDto
    export type CreateArticleMutationError = unknown

    export const useCreateArticle = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createArticle>>, TError,{data: CreateArticleDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createArticle>>,
        TError,
        {data: CreateArticleDto},
        TContext
      > => {
      return useMutation(getCreateArticleMutationOptions(options), queryClient);
    }
    
export type getAllArticlesResponse200 = {
  data: ArticlesResponseDto
  status: 200
}

export type getAllArticlesResponseSuccess = (getAllArticlesResponse200) & {
  headers: Headers;
};
;

export type getAllArticlesResponse = (getAllArticlesResponseSuccess)

export const getGetAllArticlesUrl = (params?: GetAllArticlesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/articles?${stringifiedParams}` : `/api/articles`
}

export const getAllArticles = async (params?: GetAllArticlesParams, options?: RequestInit): Promise<getAllArticlesResponse> => {
  
  return customInstance<getAllArticlesResponse>(getGetAllArticlesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetAllArticlesQueryKey = (params?: GetAllArticlesParams,) => {
    return [
    `/api/articles`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAllArticlesQueryOptions = <TData = Awaited<ReturnType<typeof getAllArticles>>, TError = unknown>(params?: GetAllArticlesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllArticles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllArticlesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllArticles>>> = ({ signal }) => getAllArticles(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn,   error: 'AxiosError<ErrorResponseDto>',  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllArticles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllArticlesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllArticles>>>
export type GetAllArticlesQueryError = unknown


export function useGetAllArticles<TData = Awaited<ReturnType<typeof getAllArticles>>, TError = unknown>(
 params: undefined |  GetAllArticlesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllArticles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllArticles>>,
          TError,
          Awaited<ReturnType<typeof getAllArticles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllArticles<TData = Awaited<ReturnType<typeof getAllArticles>>, TError = unknown>(
 params?: GetAllArticlesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllArticles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllArticles>>,
          TError,
          Awaited<ReturnType<typeof getAllArticles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllArticles<TData = Awaited<ReturnType<typeof getAllArticles>>, TError = unknown>(
 params?: GetAllArticlesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllArticles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllArticles<TData = Awaited<ReturnType<typeof getAllArticles>>, TError = unknown>(
 params?: GetAllArticlesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllArticles>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllArticlesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type getArticleResponse200 = {
  data: ArticleEntity
  status: 200
}

export type getArticleResponseSuccess = (getArticleResponse200) & {
  headers: Headers;
};
;

export type getArticleResponse = (getArticleResponseSuccess)

export const getGetArticleUrl = (id: number,) => {


  

  return `/api/articles/${id}`
}

export const getArticle = async (id: number, options?: RequestInit): Promise<getArticleResponse> => {
  
  return customInstance<getArticleResponse>(getGetArticleUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetArticleQueryKey = (id: number,) => {
    return [
    `/api/articles/${id}`
    ] as const;
    }

    
export const getGetArticleQueryOptions = <TData = Awaited<ReturnType<typeof getArticle>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticle>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetArticleQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getArticle>>> = ({ signal }) => getArticle(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id),  error: 'AxiosError<ErrorResponseDto>',  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getArticle>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetArticleQueryResult = NonNullable<Awaited<ReturnType<typeof getArticle>>>
export type GetArticleQueryError = unknown


export function useGetArticle<TData = Awaited<ReturnType<typeof getArticle>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticle>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getArticle>>,
          TError,
          Awaited<ReturnType<typeof getArticle>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetArticle<TData = Awaited<ReturnType<typeof getArticle>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticle>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getArticle>>,
          TError,
          Awaited<ReturnType<typeof getArticle>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetArticle<TData = Awaited<ReturnType<typeof getArticle>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticle>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetArticle<TData = Awaited<ReturnType<typeof getArticle>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getArticle>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetArticleQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type updateArticleResponse200 = {
  data: ArticleEntity
  status: 200
}

export type updateArticleResponseSuccess = (updateArticleResponse200) & {
  headers: Headers;
};
;

export type updateArticleResponse = (updateArticleResponseSuccess)

export const getUpdateArticleUrl = (id: number,) => {


  

  return `/api/articles/${id}`
}

export const updateArticle = async (id: number,
    updateArticleDto: UpdateArticleDto, options?: RequestInit): Promise<updateArticleResponse> => {
  
  return customInstance<updateArticleResponse>(getUpdateArticleUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateArticleDto,)
  }
);}
  



export const getUpdateArticleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateArticle>>, TError,{id: number;data: UpdateArticleDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateArticle>>, TError,{id: number;data: UpdateArticleDto}, TContext> => {

const mutationKey = ['updateArticle'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateArticle>>, {id: number;data: UpdateArticleDto}> = (props) => {
          const {id,data} = props ?? {};

          return  updateArticle(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateArticleMutationResult = NonNullable<Awaited<ReturnType<typeof updateArticle>>>
    export type UpdateArticleMutationBody = UpdateArticleDto
    export type UpdateArticleMutationError = unknown

    export const useUpdateArticle = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateArticle>>, TError,{id: number;data: UpdateArticleDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateArticle>>,
        TError,
        {id: number;data: UpdateArticleDto},
        TContext
      > => {
      return useMutation(getUpdateArticleMutationOptions(options), queryClient);
    }
    
export type deleteArticleResponse200 = {
  data: ArticleEntity
  status: 200
}

export type deleteArticleResponseSuccess = (deleteArticleResponse200) & {
  headers: Headers;
};
;

export type deleteArticleResponse = (deleteArticleResponseSuccess)

export const getDeleteArticleUrl = (id: number,) => {


  

  return `/api/articles/${id}`
}

export const deleteArticle = async (id: number, options?: RequestInit): Promise<deleteArticleResponse> => {
  
  return customInstance<deleteArticleResponse>(getDeleteArticleUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  



export const getDeleteArticleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteArticle>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteArticle>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteArticle'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteArticle>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteArticle(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteArticleMutationResult = NonNullable<Awaited<ReturnType<typeof deleteArticle>>>
    
    export type DeleteArticleMutationError = unknown

    export const useDeleteArticle = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteArticle>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteArticle>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteArticleMutationOptions(options), queryClient);
    }
    
export type createCommentResponse201 = {
  data: CommentEntity
  status: 201
}

export type createCommentResponseSuccess = (createCommentResponse201) & {
  headers: Headers;
};
;

export type createCommentResponse = (createCommentResponseSuccess)

export const getCreateCommentUrl = () => {


  

  return `/api/comments`
}

export const createComment = async (createCommentDto: CreateCommentDto, options?: RequestInit): Promise<createCommentResponse> => {
  
  return customInstance<createCommentResponse>(getCreateCommentUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCommentDto,)
  }
);}
  



export const getCreateCommentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createComment>>, TError,{data: CreateCommentDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createComment>>, TError,{data: CreateCommentDto}, TContext> => {

const mutationKey = ['createComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createComment>>, {data: CreateCommentDto}> = (props) => {
          const {data} = props ?? {};

          return  createComment(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCommentMutationResult = NonNullable<Awaited<ReturnType<typeof createComment>>>
    export type CreateCommentMutationBody = CreateCommentDto
    export type CreateCommentMutationError = unknown

    export const useCreateComment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createComment>>, TError,{data: CreateCommentDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createComment>>,
        TError,
        {data: CreateCommentDto},
        TContext
      > => {
      return useMutation(getCreateCommentMutationOptions(options), queryClient);
    }
    
export type getCommentsByArticleResponse200 = {
  data: CommentEntity[]
  status: 200
}

export type getCommentsByArticleResponseSuccess = (getCommentsByArticleResponse200) & {
  headers: Headers;
};
;

export type getCommentsByArticleResponse = (getCommentsByArticleResponseSuccess)

export const getGetCommentsByArticleUrl = (articleId: number,) => {


  

  return `/api/comments/article/${articleId}`
}

export const getCommentsByArticle = async (articleId: number, options?: RequestInit): Promise<getCommentsByArticleResponse> => {
  
  return customInstance<getCommentsByArticleResponse>(getGetCommentsByArticleUrl(articleId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetCommentsByArticleQueryKey = (articleId: number,) => {
    return [
    `/api/comments/article/${articleId}`
    ] as const;
    }

    
export const getGetCommentsByArticleQueryOptions = <TData = Awaited<ReturnType<typeof getCommentsByArticle>>, TError = unknown>(articleId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommentsByArticle>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCommentsByArticleQueryKey(articleId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCommentsByArticle>>> = ({ signal }) => getCommentsByArticle(articleId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(articleId),  error: 'AxiosError<ErrorResponseDto>',  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCommentsByArticle>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCommentsByArticleQueryResult = NonNullable<Awaited<ReturnType<typeof getCommentsByArticle>>>
export type GetCommentsByArticleQueryError = unknown


export function useGetCommentsByArticle<TData = Awaited<ReturnType<typeof getCommentsByArticle>>, TError = unknown>(
 articleId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommentsByArticle>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCommentsByArticle>>,
          TError,
          Awaited<ReturnType<typeof getCommentsByArticle>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCommentsByArticle<TData = Awaited<ReturnType<typeof getCommentsByArticle>>, TError = unknown>(
 articleId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommentsByArticle>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCommentsByArticle>>,
          TError,
          Awaited<ReturnType<typeof getCommentsByArticle>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCommentsByArticle<TData = Awaited<ReturnType<typeof getCommentsByArticle>>, TError = unknown>(
 articleId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommentsByArticle>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCommentsByArticle<TData = Awaited<ReturnType<typeof getCommentsByArticle>>, TError = unknown>(
 articleId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCommentsByArticle>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCommentsByArticleQueryOptions(articleId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export type deleteCommentResponse200 = {
  data: CommentEntity
  status: 200
}

export type deleteCommentResponseSuccess = (deleteCommentResponse200) & {
  headers: Headers;
};
;

export type deleteCommentResponse = (deleteCommentResponseSuccess)

export const getDeleteCommentUrl = (id: number,) => {


  

  return `/api/comments/${id}`
}

export const deleteComment = async (id: number, options?: RequestInit): Promise<deleteCommentResponse> => {
  
  return customInstance<deleteCommentResponse>(getDeleteCommentUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  



export const getDeleteCommentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteComment>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteComment>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteComment>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteComment(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCommentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteComment>>>
    
    export type DeleteCommentMutationError = unknown

    export const useDeleteComment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteComment>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteComment>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteCommentMutationOptions(options), queryClient);
    }
