/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Temp title
 * OpenAPI spec version: 1.0
 */
import type { ArticleAuthorName } from './articleAuthorName';

export interface ArticleAuthor {
  id: number;
  /** @nullable */
  name?: ArticleAuthorName;
  email: string;
}
