/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Temp title
 * OpenAPI spec version: 1.0
 */
import type { CommentAuthorName } from './commentAuthorName';

export interface CommentAuthor {
  id: number;
  /** @nullable */
  name?: CommentAuthorName;
  email: string;
}
