/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Temp title
 * OpenAPI spec version: 1.0
 */
import type { CommentAuthor } from './commentAuthor';

export interface CommentEntity {
  id: number;
  body: string;
  createdAt: string;
  updatedAt: string;
  articleId: number;
  authorId: number;
  author?: CommentAuthor;
}
