/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Temp title
 * OpenAPI spec version: 1.0
 */

export interface UpdateArticleDto {
  title?: string;
  description?: string;
  body?: string;
  published?: boolean;
}
