/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Temp title
 * OpenAPI spec version: 1.0
 */
import type { UserEntityName } from './userEntityName';

export interface UserEntity {
  id: number;
  createdAt: string;
  updatedAt: string;
  name: UserEntityName;
  email: string;
}
