/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/_unauthorized'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthorizedRouteImport } from './routes/_authorized'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as UnauthorizedAuthRouteImport } from './routes/_unauthorized.auth'
import { Route as PublicArticlesRouteImport } from './routes/_public.articles'
import { Route as AuthorizedProfileRouteImport } from './routes/_authorized.profile'
import { Route as PublicProfileIdRouteImport } from './routes/_public.profile.$id'
import { Route as PublicArticleIdRouteImport } from './routes/_public.article.$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/_unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedRoute = AuthorizedRouteImport.update({
  id: '/_authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const UnauthorizedAuthRoute = UnauthorizedAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => UnauthorizedRoute,
} as any)
const PublicArticlesRoute = PublicArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => PublicRoute,
} as any)
const AuthorizedProfileRoute = AuthorizedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthorizedRoute,
} as any)
const PublicProfileIdRoute = PublicProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => PublicRoute,
} as any)
const PublicArticleIdRoute = PublicArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/profile': typeof AuthorizedProfileRoute
  '/articles': typeof PublicArticlesRoute
  '/auth': typeof UnauthorizedAuthRoute
  '/article/$id': typeof PublicArticleIdRoute
  '/profile/$id': typeof PublicProfileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/profile': typeof AuthorizedProfileRoute
  '/articles': typeof PublicArticlesRoute
  '/auth': typeof UnauthorizedAuthRoute
  '/article/$id': typeof PublicArticleIdRoute
  '/profile/$id': typeof PublicProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authorized': typeof AuthorizedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_unauthorized': typeof UnauthorizedRouteWithChildren
  '/_authorized/profile': typeof AuthorizedProfileRoute
  '/_public/articles': typeof PublicArticlesRoute
  '/_unauthorized/auth': typeof UnauthorizedAuthRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/article/$id': typeof PublicArticleIdRoute
  '/_public/profile/$id': typeof PublicProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/articles'
    | '/auth'
    | '/article/$id'
    | '/profile/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profile' | '/articles' | '/auth' | '/article/$id' | '/profile/$id'
  id:
    | '__root__'
    | '/_authorized'
    | '/_public'
    | '/_unauthorized'
    | '/_authorized/profile'
    | '/_public/articles'
    | '/_unauthorized/auth'
    | '/_public/'
    | '/_public/article/$id'
    | '/_public/profile/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthorizedRoute: typeof AuthorizedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthorized': {
      id: '/_unauthorized'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized': {
      id: '/_authorized'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_unauthorized/auth': {
      id: '/_unauthorized/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof UnauthorizedAuthRouteImport
      parentRoute: typeof UnauthorizedRoute
    }
    '/_public/articles': {
      id: '/_public/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof PublicArticlesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authorized/profile': {
      id: '/_authorized/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthorizedProfileRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/_public/profile/$id': {
      id: '/_public/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof PublicProfileIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/article/$id': {
      id: '/_public/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof PublicArticleIdRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface AuthorizedRouteChildren {
  AuthorizedProfileRoute: typeof AuthorizedProfileRoute
}

const AuthorizedRouteChildren: AuthorizedRouteChildren = {
  AuthorizedProfileRoute: AuthorizedProfileRoute,
}

const AuthorizedRouteWithChildren = AuthorizedRoute._addFileChildren(
  AuthorizedRouteChildren,
)

interface PublicRouteChildren {
  PublicArticlesRoute: typeof PublicArticlesRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicArticleIdRoute: typeof PublicArticleIdRoute
  PublicProfileIdRoute: typeof PublicProfileIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicArticlesRoute: PublicArticlesRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicArticleIdRoute: PublicArticleIdRoute,
  PublicProfileIdRoute: PublicProfileIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface UnauthorizedRouteChildren {
  UnauthorizedAuthRoute: typeof UnauthorizedAuthRoute
}

const UnauthorizedRouteChildren: UnauthorizedRouteChildren = {
  UnauthorizedAuthRoute: UnauthorizedAuthRoute,
}

const UnauthorizedRouteWithChildren = UnauthorizedRoute._addFileChildren(
  UnauthorizedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthorizedRoute: AuthorizedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
