/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/_unauthorized'
import { Route as AuthorizedRouteImport } from './routes/_authorized'
import { Route as AuthorizedIndexRouteImport } from './routes/_authorized.index'
import { Route as UnauthorizedAuthRouteImport } from './routes/_unauthorized.auth'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/_unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedRoute = AuthorizedRouteImport.update({
  id: '/_authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedIndexRoute = AuthorizedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthorizedRoute,
} as any)
const UnauthorizedAuthRoute = UnauthorizedAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => UnauthorizedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthorizedIndexRoute
  '/auth': typeof UnauthorizedAuthRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthorizedIndexRoute
  '/auth': typeof UnauthorizedAuthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authorized': typeof AuthorizedRouteWithChildren
  '/_unauthorized': typeof UnauthorizedRouteWithChildren
  '/_unauthorized/auth': typeof UnauthorizedAuthRoute
  '/_authorized/': typeof AuthorizedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth'
  id:
    | '__root__'
    | '/_authorized'
    | '/_unauthorized'
    | '/_unauthorized/auth'
    | '/_authorized/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthorizedRoute: typeof AuthorizedRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthorized': {
      id: '/_unauthorized'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized': {
      id: '/_authorized'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized/': {
      id: '/_authorized/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthorizedIndexRouteImport
      parentRoute: typeof AuthorizedRoute
    }
    '/_unauthorized/auth': {
      id: '/_unauthorized/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof UnauthorizedAuthRouteImport
      parentRoute: typeof UnauthorizedRoute
    }
  }
}

interface AuthorizedRouteChildren {
  AuthorizedIndexRoute: typeof AuthorizedIndexRoute
}

const AuthorizedRouteChildren: AuthorizedRouteChildren = {
  AuthorizedIndexRoute: AuthorizedIndexRoute,
}

const AuthorizedRouteWithChildren = AuthorizedRoute._addFileChildren(
  AuthorizedRouteChildren,
)

interface UnauthorizedRouteChildren {
  UnauthorizedAuthRoute: typeof UnauthorizedAuthRoute
}

const UnauthorizedRouteChildren: UnauthorizedRouteChildren = {
  UnauthorizedAuthRoute: UnauthorizedAuthRoute,
}

const UnauthorizedRouteWithChildren = UnauthorizedRoute._addFileChildren(
  UnauthorizedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthorizedRoute: AuthorizedRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
