name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: set lower case owner name
        shell: bash
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/dlsia-server:latest

      - uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/dlsia-client:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/DLSIA

            docker-compose pull

            docker-compose up -d \
              --force-recreate \
              --remove-orphans

            docker image prune -f
